"""
    GrowCab API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401
import sys  # noqa: F401

from GrowCabApi.api_client import ApiClient, Endpoint as _Endpoint
from GrowCabApi.model_utils import (  # noqa: F401
    check_allowed_values,
    check_validations,
    date,
    datetime,
    file_type,
    none_type,
    validate_and_convert_types
)
from GrowCabApi.model.editable_measure_group import EditableMeasureGroup
from GrowCabApi.model.error import Error
from GrowCabApi.model.measure_group import MeasureGroup


class MeasureGroupApi(object):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

        def __get_latest_measure_group(
            self,
            chamber_id,
            **kwargs
        ):
            """get_latest_measure_group  # noqa: E501

            This method makes a synchronous HTTP request by default. To make an
            asynchronous HTTP request, please pass async_req=True

            >>> thread = api.get_latest_measure_group(chamber_id, async_req=True)
            >>> result = thread.get()

            Args:
                chamber_id (int):

            Keyword Args:
                _return_http_data_only (bool): response data without head status
                    code and headers. Default is True.
                _preload_content (bool): if False, the urllib3.HTTPResponse object
                    will be returned without reading/decoding response data.
                    Default is True.
                _request_timeout (float/tuple): timeout setting for this request. If one
                    number provided, it will be total request timeout. It can also
                    be a pair (tuple) of (connection, read) timeouts.
                    Default is None.
                _check_input_type (bool): specifies if type checking
                    should be done one the data sent to the server.
                    Default is True.
                _check_return_type (bool): specifies if type checking
                    should be done one the data received from the server.
                    Default is True.
                _host_index (int/None): specifies the index of the server
                    that we want to use.
                    Default is read from the configuration.
                async_req (bool): execute request asynchronously

            Returns:
                MeasureGroup
                    If the method is called asynchronously, returns the request
                    thread.
            """
            kwargs['async_req'] = kwargs.get(
                'async_req', False
            )
            kwargs['_return_http_data_only'] = kwargs.get(
                '_return_http_data_only', True
            )
            kwargs['_preload_content'] = kwargs.get(
                '_preload_content', True
            )
            kwargs['_request_timeout'] = kwargs.get(
                '_request_timeout', None
            )
            kwargs['_check_input_type'] = kwargs.get(
                '_check_input_type', True
            )
            kwargs['_check_return_type'] = kwargs.get(
                '_check_return_type', True
            )
            kwargs['_host_index'] = kwargs.get('_host_index')
            kwargs['chamber_id'] = \
                chamber_id
            return self.call_with_http_info(**kwargs)

        self.get_latest_measure_group = _Endpoint(
            settings={
                'response_type': (MeasureGroup,),
                'auth': [],
                'endpoint_path': '/api/measure_group/{chamber_id}',
                'operation_id': 'get_latest_measure_group',
                'http_method': 'GET',
                'servers': None,
            },
            params_map={
                'all': [
                    'chamber_id',
                ],
                'required': [
                    'chamber_id',
                ],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                    'chamber_id',
                ]
            },
            root_map={
                'validations': {
                    ('chamber_id',): {

                        'inclusive_minimum': 0,
                    },
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'chamber_id':
                        (int,),
                },
                'attribute_map': {
                    'chamber_id': 'chamber_id',
                },
                'location_map': {
                    'chamber_id': 'path',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [
                    'application/json'
                ],
                'content_type': [],
            },
            api_client=api_client,
            callable=__get_latest_measure_group
        )

        def __put_latest_measure_group(
            self,
            editable_measure_group,
            **kwargs
        ):
            """put_latest_measure_group  # noqa: E501

            This method makes a synchronous HTTP request by default. To make an
            asynchronous HTTP request, please pass async_req=True

            >>> thread = api.put_latest_measure_group(editable_measure_group, async_req=True)
            >>> result = thread.get()

            Args:
                editable_measure_group (EditableMeasureGroup):

            Keyword Args:
                _return_http_data_only (bool): response data without head status
                    code and headers. Default is True.
                _preload_content (bool): if False, the urllib3.HTTPResponse object
                    will be returned without reading/decoding response data.
                    Default is True.
                _request_timeout (float/tuple): timeout setting for this request. If one
                    number provided, it will be total request timeout. It can also
                    be a pair (tuple) of (connection, read) timeouts.
                    Default is None.
                _check_input_type (bool): specifies if type checking
                    should be done one the data sent to the server.
                    Default is True.
                _check_return_type (bool): specifies if type checking
                    should be done one the data received from the server.
                    Default is True.
                _host_index (int/None): specifies the index of the server
                    that we want to use.
                    Default is read from the configuration.
                async_req (bool): execute request asynchronously

            Returns:
                MeasureGroup
                    If the method is called asynchronously, returns the request
                    thread.
            """
            kwargs['async_req'] = kwargs.get(
                'async_req', False
            )
            kwargs['_return_http_data_only'] = kwargs.get(
                '_return_http_data_only', True
            )
            kwargs['_preload_content'] = kwargs.get(
                '_preload_content', True
            )
            kwargs['_request_timeout'] = kwargs.get(
                '_request_timeout', None
            )
            kwargs['_check_input_type'] = kwargs.get(
                '_check_input_type', True
            )
            kwargs['_check_return_type'] = kwargs.get(
                '_check_return_type', True
            )
            kwargs['_host_index'] = kwargs.get('_host_index')
            kwargs['editable_measure_group'] = \
                editable_measure_group
            return self.call_with_http_info(**kwargs)

        self.put_latest_measure_group = _Endpoint(
            settings={
                'response_type': (MeasureGroup,),
                'auth': [],
                'endpoint_path': '/api/measure_group',
                'operation_id': 'put_latest_measure_group',
                'http_method': 'PUT',
                'servers': None,
            },
            params_map={
                'all': [
                    'editable_measure_group',
                ],
                'required': [
                    'editable_measure_group',
                ],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'editable_measure_group':
                        (EditableMeasureGroup,),
                },
                'attribute_map': {
                },
                'location_map': {
                    'editable_measure_group': 'body',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [
                    'application/json'
                ],
                'content_type': [
                    'application/json'
                ]
            },
            api_client=api_client,
            callable=__put_latest_measure_group
        )
