"""
    GrowCab API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import GrowCabApi
from GrowCabApi.model.chamber_sensor import ChamberSensor
globals()['ChamberSensor'] = ChamberSensor
from GrowCabApi.model.chamber import Chamber


class TestChamber(unittest.TestCase):
    """Chamber unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testChamber(self):
        """Test Chamber"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Chamber()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
