"""
    GrowCab API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import GrowCabApi
from GrowCabApi.model.chamber_actuator import ChamberActuator
globals()['ChamberActuator'] = ChamberActuator
from GrowCabApi.model.actuator_measure import ActuatorMeasure


class TestActuatorMeasure(unittest.TestCase):
    """ActuatorMeasure unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testActuatorMeasure(self):
        """Test ActuatorMeasure"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ActuatorMeasure()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
