"""
    GrowCab API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import GrowCabApi
from GrowCabApi.model.editable_actuator_measure import EditableActuatorMeasure


class TestEditableActuatorMeasure(unittest.TestCase):
    """EditableActuatorMeasure unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEditableActuatorMeasure(self):
        """Test EditableActuatorMeasure"""
        # FIXME: construct object with mandatory attributes with example values
        # model = EditableActuatorMeasure()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
