"""
    GrowCab API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import GrowCabApi
from GrowCabApi.model.unit import Unit
globals()['Unit'] = Unit
from GrowCabApi.model.expected_measure import ExpectedMeasure


class TestExpectedMeasure(unittest.TestCase):
    """ExpectedMeasure unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testExpectedMeasure(self):
        """Test ExpectedMeasure"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ExpectedMeasure()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
