"""
    GrowCab API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import unittest

import GrowCabApi
from GrowCabApi.api.sensor_api import SensorApi  # noqa: E501


class TestSensorApi(unittest.TestCase):
    """SensorApi unit test stubs"""

    def setUp(self):
        self.api = SensorApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_sensor(self):
        """Test case for delete_sensor

        """
        pass

    def test_get_sensor(self):
        """Test case for get_sensor

        """
        pass

    def test_patch_sensor(self):
        """Test case for patch_sensor

        """
        pass


if __name__ == '__main__':
    unittest.main()
