"""
    GrowCab API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import unittest

import GrowCabApi
from GrowCabApi.api.measure_group_api import MeasureGroupApi  # noqa: E501


class TestMeasureGroupApi(unittest.TestCase):
    """MeasureGroupApi unit test stubs"""

    def setUp(self):
        self.api = MeasureGroupApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_latest_measure_group(self):
        """Test case for get_latest_measure_group

        """
        pass

    def test_put_latest_measure_group(self):
        """Test case for put_latest_measure_group

        """
        pass


if __name__ == '__main__':
    unittest.main()
