"""
    GrowCab API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import GrowCabApi
from GrowCabApi.model.sensor_unit import SensorUnit
globals()['SensorUnit'] = SensorUnit
from GrowCabApi.model.measure import Measure


class TestMeasure(unittest.TestCase):
    """Measure unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMeasure(self):
        """Test Measure"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Measure()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
