"""
    GrowCab API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import GrowCabApi
from GrowCabApi.model.editable_actuator_measure import EditableActuatorMeasure
from GrowCabApi.model.editable_sensor_measure import EditableSensorMeasure
globals()['EditableActuatorMeasure'] = EditableActuatorMeasure
globals()['EditableSensorMeasure'] = EditableSensorMeasure
from GrowCabApi.model.editable_measure_group import EditableMeasureGroup


class TestEditableMeasureGroup(unittest.TestCase):
    """EditableMeasureGroup unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEditableMeasureGroup(self):
        """Test EditableMeasureGroup"""
        # FIXME: construct object with mandatory attributes with example values
        # model = EditableMeasureGroup()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
