"""
    GrowCab API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import GrowCabApi
from GrowCabApi.model.chamber_sensor import ChamberSensor
from GrowCabApi.model.sensor_unit import SensorUnit
globals()['ChamberSensor'] = ChamberSensor
globals()['SensorUnit'] = SensorUnit
from GrowCabApi.model.sensor_measure import SensorMeasure


class TestSensorMeasure(unittest.TestCase):
    """SensorMeasure unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSensorMeasure(self):
        """Test SensorMeasure"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SensorMeasure()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
