"""
    GrowCab API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import unittest

import GrowCabApi
from GrowCabApi.api.configurations_api import ConfigurationsApi  # noqa: E501


class TestConfigurationsApi(unittest.TestCase):
    """ConfigurationsApi unit test stubs"""

    def setUp(self):
        self.api = ConfigurationsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_configurations(self):
        """Test case for get_configurations

        Get the list of configurations  # noqa: E501
        """
        pass

    def test_put_configuration(self):
        """Test case for put_configuration

        Stores a new configuration  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
