"""
    GrowCab API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import GrowCabApi
from GrowCabApi.model.chamber import Chamber
globals()['Chamber'] = Chamber
from GrowCabApi.model.sensor1 import Sensor1


class TestSensor1(unittest.TestCase):
    """Sensor1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSensor1(self):
        """Test Sensor1"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Sensor1()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
