"""
    GrowCab API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import GrowCabApi
from GrowCabApi.model.unit import Unit


class TestUnit(unittest.TestCase):
    """Unit unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUnit(self):
        """Test Unit"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Unit()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
