"""
    GrowCab API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import unittest

import GrowCabApi
from GrowCabApi.api.chambers_api import ChambersApi  # noqa: E501


class TestChambersApi(unittest.TestCase):
    """ChambersApi unit test stubs"""

    def setUp(self):
        self.api = ChambersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_chamber(self):
        """Test case for get_chamber

        Get the chamber and related objects :param chamber_id: ID of the chamber :return: Returns a Chamber object  # noqa: E501
        """
        pass

    def test_get_chamber_sensors(self):
        """Test case for get_chamber_sensors

        Get the sensors for a chamber :param chamber_id: :return:  # noqa: E501
        """
        pass

    def test_get_chamber_status(self):
        """Test case for get_chamber_status

        """
        pass

    def test_get_chamber_units(self):
        """Test case for get_chamber_units

        Get the units available for this chamber  # noqa: E501
        """
        pass

    def test_get_chambers(self):
        """Test case for get_chambers

        Get the list of configurations  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
