"""
    GrowCab API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import GrowCabApi
from GrowCabApi.model.actuator_measure import ActuatorMeasure
from GrowCabApi.model.sensor_measure import SensorMeasure
globals()['ActuatorMeasure'] = ActuatorMeasure
globals()['SensorMeasure'] = SensorMeasure
from GrowCabApi.model.measure_group import MeasureGroup


class TestMeasureGroup(unittest.TestCase):
    """MeasureGroup unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMeasureGroup(self):
        """Test MeasureGroup"""
        # FIXME: construct object with mandatory attributes with example values
        # model = MeasureGroup()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
