"""
    GrowCab API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import GrowCabApi
from GrowCabApi.model.expected_measure import ExpectedMeasure
globals()['ExpectedMeasure'] = ExpectedMeasure
from GrowCabApi.model.editable_configuration import EditableConfiguration


class TestEditableConfiguration(unittest.TestCase):
    """EditableConfiguration unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEditableConfiguration(self):
        """Test EditableConfiguration"""
        # FIXME: construct object with mandatory attributes with example values
        # model = EditableConfiguration()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
