"""
    GrowCab API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import GrowCabApi
from GrowCabApi.model.chamber_sensor import ChamberSensor


class TestChamberSensor(unittest.TestCase):
    """ChamberSensor unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testChamberSensor(self):
        """Test ChamberSensor"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ChamberSensor()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
