"""
    GrowCab API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import unittest

import GrowCabApi
from GrowCabApi.api.chamber_schedule_api import ChamberScheduleApi  # noqa: E501


class TestChamberScheduleApi(unittest.TestCase):
    """ChamberScheduleApi unit test stubs"""

    def setUp(self):
        self.api = ChamberScheduleApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_chamber_schedule(self):
        """Test case for get_chamber_schedule

        """
        pass

    def test_get_chamber_schedule_unit(self):
        """Test case for get_chamber_schedule_unit

        """
        pass


if __name__ == '__main__':
    unittest.main()
