"""
    GrowCab API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import GrowCabApi
from GrowCabApi.model.expected_measure import ExpectedMeasure
globals()['ExpectedMeasure'] = ExpectedMeasure
from GrowCabApi.model.configuration1 import Configuration1


class TestConfiguration1(unittest.TestCase):
    """Configuration1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testConfiguration1(self):
        """Test Configuration1"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Configuration1()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
