"""
    GrowCab API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import unittest

import GrowCabApi
from GrowCabApi.api.sensors_api import SensorsApi  # noqa: E501


class TestSensorsApi(unittest.TestCase):
    """SensorsApi unit test stubs"""

    def setUp(self):
        self.api = SensorsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_sensors(self):
        """Test case for get_sensors

        Get the list of sensors  # noqa: E501
        """
        pass

    def test_put_sensor(self):
        """Test case for put_sensor

        Stores a new sensor  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
