"""
    GrowCab API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import GrowCabApi
from GrowCabApi.model.chamber import Chamber
globals()['Chamber'] = Chamber
from GrowCabApi.model.editable_sensor import EditableSensor


class TestEditableSensor(unittest.TestCase):
    """EditableSensor unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEditableSensor(self):
        """Test EditableSensor"""
        # FIXME: construct object with mandatory attributes with example values
        # model = EditableSensor()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
