"""
    GrowCab API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import GrowCabApi
from GrowCabApi.model.actuator import Actuator
globals()['Actuator'] = Actuator
from GrowCabApi.model.chamber_actuator import ChamberActuator


class TestChamberActuator(unittest.TestCase):
    """ChamberActuator unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testChamberActuator(self):
        """Test ChamberActuator"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ChamberActuator()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
